# https://docs.docker.com/compose/compose-file/
version: "3.9"
services:
  netwatch:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - queue
  database:
    image: mysql:8.0.31
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=netwatch
      - MYSQL_USER=netwatch
      - MYSQL_PASSWORD=__CHANGE_ME!__
    ports:
      - '3307:3306'
    volumes:
      - ./db_data:/var/lib/mysql
  queue:
    image: rabbitmq:3.11.2-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=netwatch
      - RABBITMQ_DEFAULT_PASS=__CHANGE_ME!__
    ports:
      - "5672:5672"
      - "15672:15672" # Management Web UI
volumes:
  database:
    driver: local
